apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wc-data-producer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: kpops
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bakdata/kpops-examples.git
    targetRevision: test/argocd
    path: word-count/argo/pipeline/counter
