---
# Source: producer-app/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: wc-data-producer
  labels:
    app: wc-data-producer
    chart: producer-app-2.9.0
    release: wc-data-producer
spec:
  template:
    metadata:
      labels:
        app: wc-data-producer
        release: wc-data-producer
    spec:
      restartPolicy: OnFailure
      containers:
      - name: wc-data-producer
        image: "bakdata/kpops-demo-sentence-producer:1.0.0"
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 500m
            memory: 2G
          requests:
            cpu: 200m
            memory: 300Mi
        env:
          - name: ENV_PREFIX
            value: APP_
          - name: "APP_BROKERS"
            value: "my-cluster-kafka-0.my-cluster-kafka-brokers.infrastructure.svc:9092"
          - name: "APP_SCHEMA_REGISTRY_URL"
            value: 
          - name: "APP_DEBUG"
            value: "false"
          - name: "APP_OUTPUT_TOPIC"
            value: "wc-data-producer-topic"
          - name: JAVA_TOOL_OPTIONS
            value: '-XX:MaxRAMPercentage=75.0
                    '
  backoffLimit: 6
---
# output topic producer
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wc-data-producer-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
# Source: streams-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wc-word-counter
  labels:
    app: wc-word-counter
    chart: streams-app-2.9.0
    release: wc-word-counter
    pipeline: kpops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wc-word-counter
      release: wc-word-counter
  template:
    metadata:
      labels:
        app: wc-word-counter
        release: wc-word-counter
        pipeline: kpops
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - wc-word-counter
      containers:
        - name: wc-word-counter
          image: "bakdata/kpops-demo-word-count-app:1.0.0"
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: 500m
              memory: 2G
            requests:
              cpu: 200m
              memory: 300Mi
          env:
            - name: ENV_PREFIX
              value: APP_
            - name: "APP_VOLATILE_GROUP_INSTANCE_ID"
              value: "true"
            - name: "APP_BROKERS"
              value: "my-cluster-kafka-0.my-cluster-kafka-brokers.infrastructure.svc:9092"
            - name: "APP_SCHEMA_REGISTRY_URL"
              value: ""
            - name: "APP_DEBUG"
              value: "false"
            - name: "APP_INPUT_TOPICS"
              value: "wc-data-producer-topic"
            - name: "APP_OUTPUT_TOPIC"
              value: "wc-word-counter-topic"
            - name: "APP_ERROR_TOPIC"
              value: "wc-word-counter-dead-letter-topic"
            - name: "APP_PRODUCTIVE"
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: '-Dcom.sun.management.jmxremote.port=5555
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.ssl=false
                -XX:MaxRAMPercentage=75.0'
---
# output topic streams app
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wc-word-counter-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
# error topic streams app
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wc-word-counter-dead-letter-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
