apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kpops-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: word-count
    repoURL: 'https://github.com/bakdata/kpops-examples'
    targetRevision: test/argocd
    plugin:
      name: kpops-deploy
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
