kafka_brokers: "http://k8kafka-cp-kafka-headless.kpops.svc.cluster.local:9092"

kafka_rest:
  url: "http://localhost:8082"

kafka_connect:
  url: "http://localhost:8083"

schema_registry:
  enabled: true
  url: "http://k8kafka-cp-schema-registry.kpops.svc.cluster.local:8081"

defaults_path: "."

topic_name_config:
  default_error_topic_name: "${component.name}-dead-letter-topic"
  default_output_topic_name: "${component.name}-topic"
