nameOverride: word-count-wordcounter

replicaCount: 1

image: us.gcr.io/gcp-bakdata-cluster/kpops-word-count-streams-app
imageTag: latest
imagePullPolicy: Always

streams:
  brokers: "http://k8kafka-cp-kafka-headless.infrastructure.svc.cluster.local:9092"
  schemaRegistryUrl: "http://k8kafka-cp-schema-registry.infrastructure.svc.cluster.local:8081"
  inputTopics: word-count-raw-data-producer-topic
  outputTopic: word-count-countedwords-topic

annotations:
  consumerGroup: "word-counter-group"

prometheus:
  jmx:
    enabled: false

debug: true
