nameOverride: word-count-data-producer

replicaCount: 1

image: us.gcr.io/gcp-bakdata-cluster/kpops-word-count-data-producer
imageTag: latest
imagePullPolicy: Always
streams:
  brokers: "k8kafka-cp-kafka-headless:9092"
  outputTopic: word-count-raw-data-producer-topic
prometheus:
  jmx:
    enabled: false

debug: true
