nameOverride: word-count-wordcounter

replicaCount: 1

image: bakdata/kpops-demo-word-count-app
imageTag: 1.0.0
imagePullPolicy: Always

streams:
  brokers: "k8kafka-cp-kafka-headless:9092"
  inputTopics: word-count-raw-data-producer-topic
  outputTopic: word-count-countedwords-topic
  productive: false

annotations:
  consumerGroup: "word-counter-group"

prometheus:
  jmx:
    enabled: false

debug: true
