- type: producer
  name: wc-data-producer
  namespace: kpops
  app:
    image: bakdata/kpops-demo-sentence-producer
    imageTag: 1.0.0
    prometheus:
      jmx:
        enabled: false
    debug: true

- type: streams-app
  name: wc-word-counter
  namespace: kpops
  app:
    replicaCount: 1
    image: bakdata/kpops-demo-word-count-app
    imageTag: 1.0.0  
    commandLine:
      PRODUCTIVE: false
    streams:
      brokers: "k8kafka-cp-kafka-headless:9092"
    prometheus:
      jmx:
        enabled: false
    debug: true

- type: kafka-sink-connector
  name: RedisSinkConnector
  namespace: kpops
  app:
    name: RedisSinkConnector
    connector.class: com.github.jcustenborder.kafka.connect.redis.RedisSinkConnector
    redis.hosts: redis-headless:6379
    redis.database: 0
    topics: examples-bakdata-word-count-wc-word-counter-topic
    tasks.max: 1
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
