nameOverride: word-count-data-producer

replicaCount: 1

image: bakdata/kpops-demo-sentence-producer
imageTag: 2.0.0
imagePullPolicy: Always
kafka:
  bootstrapServers: "k8kafka-cp-kafka-headless:9092"
  outputTopic: word-count-raw-data-producer-topic
prometheus:
  jmx:
    enabled: false

