---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    bakdata.com/cluster: bakdata-strimzi-cluster
  name: word-count-data-producer-topic
spec:
  config: {}
  partitions: 3
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    bakdata.com/cluster: bakdata-strimzi-cluster
  name: word-count-word-count-app-topic
spec:
  config:
    cleanup.policy: compact
  partitions: 3
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    bakdata.com/cluster: bakdata-strimzi-cluster
  name: word-count-word-count-app-dead-letter-topic
spec:
  config: {}
  partitions: 1
  replicas: 1

