apiVersion: com.bakdata.kafka/v1
kind: ProducerApp
metadata:
  name: wc-sentecne-producer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  brokers: http://strimzi-k8kafka-kafka-bootstrap.infrastructure.svc.cluster.local:9092
  image: us.gcr.io/gcp-bakdata-cluster/kpops-word-count-data-producer
  imagePullPolicy: Always
  imageTag: no-sr-snapshot
  name: wc-sentecne-producer
  replicaCount: 1
---
# output topic producer
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wc-sentence-topic
  labels:
    strimzi.io/cluster: strimzi-k8kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  partitions: 1
  replicas: 3