apiVersion: com.bakdata.kafka/v1
kind: StreamsApp
metadata:
  name: wc-word-count-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  brokers: http://strimzi-k8kafka-kafka-bootstrap.infrastructure.svc.cluster.local:9092
  image: us.gcr.io/gcp-bakdata-cluster/kpops-word-count-streams-app
  imagePullPolicy: Always
  imageTag: no-sr-snapshot
  name: word-counter
  replicaCount: 1
  schemaRegistryUrl: http://k8kafka-cp-schema-registry.infrastructure.svc.cluster.local:8091
  inputTopics:
    - wc-sentence-topic
  outputTopic: wc-word-counter-topic
  errorTopic: wc-word-counter-dead-letter-topic

---
# output topic streams app
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wc-word-counter-topic
  labels:
    strimzi.io/cluster: strimzi-k8kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  partitions: 1
  replicas: 3
---
# error topic streams app
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: wc-word-counter-dead-letter-topic
  labels:
    strimzi.io/cluster: strimzi-k8kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  partitions: 1
  replicas: 3