namespace: "kpops"

applications:
    - name: wc-data-producer-clean-up
      repo: https://github.com/bakdata/kpops-examples.git
      targetRevision: test/argocd
      path: word-count/argo/pipeline/producer
      syncWave: 1

    - name: wc-word-counter-clean-up
      repo: https://github.com/bakdata/kpops-examples.git
      targetRevision: test/argocd
      path: word-count/argo/pipeline/counter
      syncWave: 2
