name: argo-app-deploy

on:
  workflow_dispatch:
  push:

jobs:
  argo-deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: GKE authentication
        uses: bakdata/ci-templates/actions/setup-credentials@1.40.0
        with:
          gke-service-account: ${{ secrets.GKE_SERVICE_ACCOUNT }}
          gke-project: ${{ secrets.GKE_PROJECT }}
          gke-region: ${{ secrets.GKE_REGION }}
          gke-cluster: ${{ secrets.GKE_CLUSTER }}

      - name: Setup environment
        uses: bakdata/ci-templates/actions/helm-setup@v1.21.0

      - name: Run kubectl apply
        shell: bash
        run: kubectl apply -f argo-manifest.yaml
