name: Build, Test and Publish

on:
  push:
    tags: [ '**' ]
    branches: [ '**' ]

env:
  DOCKER_REGISTRY: bakdata
  SENTENCE_PRODUCER_IMAGE_NAME: kpops-demo-sentence-producer
  WORD_COUNT_APPLICATION_IMAGE_NAME: kpops-demo-word-count-app
  WORKING_DIRECTORY_APP: "./word-count"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        uses: bakdata/ci-templates/actions/java-gradle-build@v1.7.0
        with:
          java-distribution: "microsoft"
          java-version: "17"
          gradle-version: "wrapper"
          working-directory: ${{env.WORKING_DIRECTORY_APP}}

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Test
        uses: bakdata/ci-templates/actions/java-gradle-test@v1.7.0
        with:
          java-distribution: "microsoft"
          java-version: "17"
          gradle-version: "wrapper"
          working-directory: ${{env.WORKING_DIRECTORY_APP}}

  build-and-publish-jib:
      name: Build and publish images
      runs-on: ubuntu-22.04
      needs: test

      steps:
        - name: Check out repository
          uses: bakdata/ci-templates/actions/checkout@1.32.0

        - name: Set up Gradle
          uses: bakdata/ci-templates/actions/java-gradle-setup@v1.16.0
          with:
            java-distribution: "microsoft"
            java-version: "17"
            gradle-version: "wrapper"

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}


        - name: Build Docker images
          run: |
            if [[ "$GITHUB_REF" =~ ^refs/tags/.* ]]; then
              ./gradlew jib \
                --info --stacktrace \
                --image=$DOCKER_REGISTRY/$SENTENCE_PRODUCER_IMAGE_NAME \
                -Djib.container.mainClass=com.bakdata.kpops.examples.SentenceProducer \
                -Djib.to.tags=latest,${GITHUB_REF/refs\/tags\//}

              ./gradlew jib \
                --info --stacktrace \
                --image=$DOCKER_REGISTRY/$WORD_COUNT_APPLICATION_IMAGE_NAME \
                -Djib.container.mainClass=com.bakdata.kpops.examples.WordCountApplication \
                -Djib.to.tags=latest,${GITHUB_REF/refs\/tags\//}
            else
              ./gradlew jib \
                --info --stacktrace \
                --image=$DOCKER_REGISTRY/$SENTENCE_PRODUCER_IMAGE_NAME \
                 -Djib.container.mainClass=com.bakdata.kpops.examples.SentenceProducer \
                 -Djib.to.tags=${{ github.run_id }}

              ./gradlew jib \
                --info --stacktrace \
                --image=$DOCKER_REGISTRY/$WORD_COUNT_APPLICATION_IMAGE_NAME \
                -Djib.container.mainClass=com.bakdata.kpops.examples.WordCountApplication \
                -Djib.to.tags=${{ github.run_id }}

          shell: bash
          working-directory: ${{env.WORKING_DIRECTORY_APP}}

  release:
    name: Create GitHub release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: build-and-publish-jib

    steps:
      - name: Release on Github
        uses: bakdata/ci-templates/actions/java-gradle-release-github@v1.4.0
        with:
          github-username: ${{ secrets.USERNAME }}
          github-token: ${{ secrets.GH_TOKEN }}
          java-distribution: "microsoft"
          java-version: "17"
          working-directory:  ${{env.WORKING_DIRECTORY_APP}}
