name: Release

env:
  WORKING_DIRECTORY_APP: "./word-count"

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        uses: bakdata/ci-templates/actions/java-gradle-build@v1.7.0
        with:
          java-distribution: "microsoft"
          java-version: "17"
          gradle-version: "wrapper"
          working-directory: ${{env.WORKING_DIRECTORY_APP}}

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Test
        uses: bakdata/ci-templates/actions/java-gradle-test@v1.7.0
        with:
          java-distribution: "microsoft"
          java-version: "17"
          gradle-version: "wrapper"
          working-directory: ${{env.WORKING_DIRECTORY_APP}}

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Check out repository
        uses: bakdata/ci-templates/actions/checkout@1.32.0
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false # required for pushing to protected branch later
          fetch-depth: 0 # required to build the changelog


      - name: Release on Github
        id: release
        uses: bakdata/ci-templates/actions/java-gradle-release@1.27.0
        with:
          release-type: ${{ inputs.release-type }}
          github-email: ${{ secrets.GH_EMAIL }}
          github-username: ${{ secrets.GH_USERNAME }}
          github-token: ${{ secrets.GH_TOKEN }}
          java-distribution: "microsoft"
          java-version: "17"
          working-directory: ${{ inputs.working-directory }}
