- type: producer-app
  name: data-producer
  values:
    image: bakdata/kpops-demo-sentence-producer

- type: streams-app
  name: word-counter
  to:
    topics:
      ${output_topic_name}:
        type: output
        configs:
          cleanup.policy: compact
  values:
    image: bakdata/kpops-demo-word-count-app
    replicaCount: 1

- type: kafka-sink-connector
  name: redis-sink-connector
  config:
    connector.class: com.github.jcustenborder.kafka.connect.redis.RedisSinkConnector
    redis.hosts: redis-headless:6379
    redis.database: 0
    tasks.max: 1
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
